# Generated by Django 2.1.5 on 2019-03-26 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Spacy',
            new_name='trainingData',
        ),
    ]
