# Generated by Django 2.1.5 on 2019-03-30 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0002_auto_20190326_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookMetaData',
            fields=[
                ('bookID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500, verbose_name='Book Title')),
                ('author', models.CharField(max_length=500, verbose_name='Book Author')),
                ('language', models.CharField(max_length=10, verbose_name='language')),
                ('rights', models.CharField(max_length=500, verbose_name='Book Rights')),
            ],
        ),
        migrations.CreateModel(
            name='BookText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookContents', models.TextField()),
                ('bookID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.BookMetaData')),
            ],
        ),
    ]
