# Generated by Django 2.1.5 on 2019-03-31 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0003_bookmetadata_booktext'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmetadata',
            name='subjects',
            field=models.BinaryField(blank=True),
        ),
    ]
