# Generated by Django 2.1.5 on 2019-03-31 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0005_auto_20190331_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmetadata',
            name='language',
            field=models.CharField(max_length=10, verbose_name='Book language'),
        ),
        migrations.AlterField(
            model_name='bookmetadata',
            name='subjects',
            field=models.BinaryField(blank=True, verbose_name='Books subjects'),
        ),
    ]
