# Generated by Django 2.1.5 on 2019-03-31 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0006_auto_20190331_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmetadata',
            name='subjects',
            field=models.BinaryField(default=str),
        ),
    ]
