# Generated by Django 2.1.5 on 2019-03-31 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0007_auto_20190331_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmetadata',
            name='subjects',
            field=models.BinaryField(blank=bool),
        ),
    ]
